name =input("what is your name :") 
age =int(input("what is your age :")) 
favourite_language =input("what is your fourite language :") 
city= input("u r which city : ")
university= input("your uni name : ")
cgpa= float(input("what is your cgpa? "))
skills= input("which skills u have worked on? ")

print("u are :"+ name)
print(f"u are {age} years old")
print("ur fourite language is "  + favourite_language)
print("so u belong to " +city)
print("u r studing in " + university)
print(f"cgpa : " , {cgpa})
print("skills : " +skills)
