print("--------------------------------")
print("      Student Information")
print("--------------------------------")

name = input("Enter Name: ")
age = input("Enter Age: ")
university = input("Enter University: ")
cgpa = input("Enter CGPA: ")
department = input("Enter Department: ")
skills = input("Enter Skills: ")

print("\n--------------------------------")
print("      Student Information")
print("--------------------------------")
print(f"Name       : {name}")
print(f"Age        : {age}")
print(f"University : {university}")
print(f"CGPA       : {cgpa}")
print(f"Department : {department}")
print(f"Skills     : {skills}")
print("--------------------------------")